AppBase/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', inicio, name="Inicio"),
    path('ag-videojuego', agregar_videojuego, name="AgregarVideojuego"),
    path('l-videojuegos', lista_videojuegos, name="ListaVideojuegos"),
    path('el-videojuegos/<int:id>', eliminar_videojuego, name="EliminarVideojuego"),
    path('ed-videojuegos/<int:id>', editar_videojuego, name="EditarVideojuego"),
    path('ag-resena', agregar_resena, name='AgregarResena'),
    path('l-resenas', lista_resenas, name='ListaResenas'),
    path('el-resenas/<int:id>', eliminar_resena, name="EliminarResena"),
    path('ed-resenas/<int:id>', editar_resena, name="EditarResena"),
    path('busq-videojuego', busqueda_videojuegos, name="BusquedaVideojuegos"),
    path('buscar-nombre', buscar_nombre, name="BuscarNombre"),
    path('buscar-genero', buscar_genero, name="BuscarGenero"),
    path('buscar-empresa', buscar_empresa, name="BuscarEmpresa"),
    path('buscar-valoracion', buscar_valoracion, name="BuscarValoracion"),
    path('about-me', AboutMe, name="AboutMe"),
    path('foro', lista_temas, name='Foro'),
    path('crear-tema', crear_tema, name='CrearTema'),
    path('ed-tema/<int:pk>', editar_tema, name='EditarTema'),
    path('el-tema/<int:pk>', eliminar_tema, name='EliminarTema'),
    path('foro/<int:pk>/', detalle_tema, name='DetalleTema'),
    path('<int:pk>/crear-coment', crear_comentario, name='CrearComentario'),
]

AppMensajes/urls.py
from django.urls import path
from .views import *

app_name = 'AppMensajes'

urlpatterns = [
    path('inbox', ConversacionListView.as_view(), name='Inbox'),
    path('nuevo-msj', ConversacionCreateView.as_view(), name='CrearConversacion'),
    path('<int:room_id>', ConversacionDetailView.as_view(), name='VerConversacion'),
    path('<int:pk>/agregar-msj/', AgregarMensajeConversacionView.as_view(), name='AgregarMensaje'),
]

ProyectoFinal/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppBase.urls')),
    path('', include('AppRegistro.urls')),
    path('', include('AppLogin.urls')),
    path('', include('AppPerfiles.urls')),
    path('', include('AppMensajes.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppMensajes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Mensajes(models.Model):
    remitente = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mensajes_enviados')
    destinatario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mensajes_recibidos')
    mensaje = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.remitente} to {self.destinatario}'

AppMensajes/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *

# Create your views here.

class ConversacionListView(LoginRequiredMixin, ListView):
    model = Mensajes
    context_object_name = 'conversaciones'
    template_name = 'conversacion_list.html'
    def get_queryset(self):
        return Mensajes.objects.filter(
            models.Q(remitente=self.request.user) | models.Q(destinatario=self.request.user)
        ).distinct().order_by('-timestamp')

class ConversacionCreateView(LoginRequiredMixin, CreateView):
    model = Mensajes
    fields = ['destinatario', 'mensaje']
    template_name = 'conversacion_create.html'
    success_url = reverse_lazy('AppMensajes:Inbox')
    def form_valid(self, form):
        remitente = self.request.user
        form.instance.remitente = remitente
        return super().form_valid(form)

class ConversacionDetailView(LoginRequiredMixin, DetailView):
    model = Mensajes
    context_object_name = 'conversacion'
    template_name = 'conversacion_detail.html'
    def get_object(self, queryset=None):
        room_id = self.kwargs['room_id']
        room = get_object_or_404(Mensajes, id=room_id)
        if room.remitente != self.request.user and room.destinatario != self.request.user:
            return redirect('AppMensajes:Inbox')
        return room

class AgregarMensajeConversacionView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        conversacion_id = kwargs['pk']
        mensaje = request.POST.get('mensaje')
        conversacion = get_object_or_404(Mensajes, id=conversacion_id)
        user = request.user
        if user == conversacion.remitente:
            destinatario = conversacion.destinatario
        elif user == conversacion.destinatario:
            destinatario = conversacion.remitente
        else:
            return redirect('AppMensajes:Inbox')
        nuevo_mensaje = Mensajes(remitente=user, destinatario=destinatario, mensaje=mensaje)
        nuevo_mensaje.save()
        return redirect(reverse_lazy('AppMensajes:VerConversacion', kwargs={'room_id': conversacion_id}))

AppMensajes/templates/conversacion_create.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'conversacion_create.css' %}">

<div class="container">
  <h1>Crear conversación</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
</div>

{% endblock %}

AppMensajes/templates/conversacion_detail.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'conversacion_detail.css' %}">

<div class="container">
    <h1>Conversación</h1>
  
    <div class="card">
      <div class="card-body">
        {% for mensaje in conversacion.mensajes.all %}
          <div class="{% if mensaje.remitente == request.user %}text-end{% endif %}">
            <strong>{{ mensaje.remitente }}:</strong> {{ mensaje.mensaje }}
          </div>
        {% empty %}
          <p>No hay mensajes en esta conversación</p>
        {% endfor %}
      </div>
    </div>
  
    <form method="post" class="mt-3" class="mt-3" action="{% url 'AppMensajes:AgregarMensaje' pk=conversacion.id %}">
      {% csrf_token %}
      <div class="mb-3">
        <label for="mensaje" class="form-label">Mensaje:</label>
        <textarea name="mensaje" id="mensaje" class="form-control" rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Enviar mensaje</button>
    </form>
</div>
{% endblock %}

AppMensajes/templates/conversacion_list.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'conversacion_list.css' %}">

<h1>Conversaciones</h1>

  <a href="{% url 'AppMensajes:CrearConversacion' %}" class="btn btn-primary mb-3">Crear conversación</a>

  <table class="table">
    <thead>
      <tr>
        <th class="columna-remitente">Remitente</th>
        <th class="columna-destinatario">Destinatario</th>
        <th class="columna-ultimomensaje">Último mensaje</th>
        <th class="columna-fecha">Fecha</th>
        <th class="columna-acciones">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for conversacion in conversaciones %}
        <tr>
          <td>{{ conversacion.remitente }}</td>
          <td>{{ conversacion.destinatario }}</td>
          <td>{{ conversacion.mensaje }}</td>
          <td>{{ conversacion.timestamp|date:"d/m/Y H:i" }}</td>
          <td><a href="{% url 'AppMensajes:VerConversacion' conversacion.id %}" class="btn btn-sm btn-outline-secondary">Ver conversación</a></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No hay conversaciones disponibles</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}