AppBase/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', inicio, name="Inicio"),
    path('ag-videojuego', agregar_videojuego, name="AgregarVideojuego"),
    path('l-videojuegos', lista_videojuegos, name="ListaVideojuegos"),
    path('el-videojuegos/<int:id>', eliminar_videojuego, name="EliminarVideojuego"),
    path('ed-videojuegos/<int:id>', editar_videojuego, name="EditarVideojuego"),
    path('ag-resena', agregar_resena, name='AgregarResena'),
    path('l-resenas', lista_resenas, name='ListaResenas'),
    path('el-resenas/<int:id>', eliminar_resena, name="EliminarResena"),
    path('ed-resenas/<int:id>', editar_resena, name="EditarResena"),
    path('busq-videojuego', busqueda_videojuegos, name="BusquedaVideojuegos"),
    path('buscar-nombre', buscar_nombre, name="BuscarNombre"),
    path('buscar-genero', buscar_genero, name="BuscarGenero"),
    path('buscar-empresa', buscar_empresa, name="BuscarEmpresa"),
    path('buscar-valoracion', buscar_valoracion, name="BuscarValoracion"),
    path('about-me', AboutMe, name="AboutMe"),
    path('foro', lista_temas, name='Foro'),
    path('crear-tema', crear_tema, name='CrearTema'),
    path('ed-tema/<int:pk>', editar_tema, name='EditarTema'),
    path('el-tema/<int:pk>', eliminar_tema, name='EliminarTema'),
    path('foro/<int:pk>/', detalle_tema, name='DetalleTema'),
    path('<int:pk>/crear-coment', crear_comentario, name='CrearComentario'),
]

AppMensajes/urls.py
from django.urls import path
from .views import *

app_name = 'AppMensajes'

urlpatterns = [
    path('inbox', ConversacionListView.as_view(), name='Inbox'),
    path('nuevo-msj', ConversacionCreateView.as_view(), name='CrearConversacion'),
    path('<int:room_id>', ConversacionDetailView.as_view(), name='VerConversacion'),
    path('<int:pk>/agregar-msj/', AgregarMensajeConversacionView.as_view(), name='AgregarMensaje'),
]

ProyectoFinal/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppBase.urls')),
    path('', include('AppRegistro.urls')),
    path('', include('AppLogin.urls')),
    path('', include('AppPerfiles.urls')),
    path('', include('AppMensajes.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppBase/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
GENERO_OPCIONES = [('aventura', 'Aventura'), ('deportes', 'Deportes'), ('estrategia', 'Estrategia'), ('rpg', 'RPG'), ('moba', 'MOBA'), ('hack_and_slash', 'Hack And Slash'), 
                   ('mmorpg', 'MMORPG'), ('shooter', 'Shooter'), ('cartas', 'Cartas'), ('city_builder', 'City Builder'), ('simulador', 'Simulador'), ('carreras', 'Carreras'), 
                   ('arcade', 'Arcade'), ('plataformas', 'Plataformas'), ('pelea', 'Pelea'), ('terror', 'Terror'), ('sigilo', 'Sigilo'), ('battle_royale', 'Battle Royale'), 
                   ('rpg_por_turnos', 'RPG Por Turnos'), ('roguelike', 'Roguelike'), ('sandbox', 'Sandbox'), ('musica', 'Música'), ('tower_defense', 'Tower Defense'), 
                   ('rts', 'RTS'), ('accion', 'Acción'), ('soul', 'Soul'),]

GENERO_OPCIONES = sorted(GENERO_OPCIONES, key=lambda x: x[1])

VALORACIONES_OPCIONES = [(i, str(i)) for i in range(1, 11)]

class Videojuego(models.Model):
    nombre = models.CharField(max_length=255)
    fecha_salida = models.DateField()
    genero = models.CharField(max_length=255, choices=GENERO_OPCIONES)
    empresa = models.CharField(max_length=255)
    descripcion = models.TextField()
    valoracion = models.IntegerField(choices=VALORACIONES_OPCIONES, null=False)
    def __str__(self):
        return f"{self.nombre} - {self.genero} - {self.empresa}"

class Resena(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    contenido = models.TextField()
    videojuego = models.ForeignKey(Videojuego, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.autor} - {self.videojuego.nombre}"

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)
    def __str__(self):
        return f"{self.user} / {self.imagen}"
    
class Tema(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    creador = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.creador} - {self.titulo}"

class Comentario(models.Model):
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    creador = models.ForeignKey(User, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE, related_name='comentarios')
    def __str__(self):
        return f"{self.creador} - {self.tema}"

AppBase/forms.py
from django import forms
from .models import *

GENERO_OPCIONES = [('aventura', 'Aventura'), ('deportes', 'Deportes'), ('estrategia', 'Estrategia'), ('rpg', 'RPG'), ('moba', 'MOBA'), ('hack and slash', 'Hack And Slash'), 
                   ('mmorpg', 'MMORPG'), ('shooter', 'Shooter'), ('cartas', 'Cartas'), ('city builder', 'City Builder'), ('simulador', 'Simulador'), ('carreras', 'Carreras'), 
                   ('arcade', 'Arcade'), ('plataformas', 'Plataformas'), ('pelea', 'Pelea'), ('terror', 'Terror'), ('sigilo', 'Sigilo'), ('battle royale', 'Battle Royale'), 
                   ('rpg por turnos', 'RPG Por Turnos'), ('roguelike', 'Roguelike'), ('sandbox', 'Sandbox'), ('musica', 'Música'), ('tower defense', 'Tower Defense'), 
                   ('rts', 'RTS'),]
GENERO_OPCIONES = sorted(GENERO_OPCIONES, key=lambda x: x[1])

VALORACIONES_OPCIONES = [(i, str(i)) for i in range(1, 11)]

class VideojuegosForm(forms.Form):
    nombre = forms.CharField(max_length=255)
    fecha_salida = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    genero = forms.CharField(max_length=255, widget=forms.Select(choices=GENERO_OPCIONES))
    empresa = forms.CharField(max_length=255)
    descripcion = forms.CharField(max_length=255)
    valoracion = forms.IntegerField(required=True, widget=forms.Select(choices=VALORACIONES_OPCIONES))

class ResenaForm(forms.ModelForm):
    class Meta:
        model = Resena
        fields = ('__all__')

class BuscarNombre(forms.Form):
    nombre = forms.CharField(label='Nombre del videojuego', max_length=255)

class BuscarGenero(forms.Form):
    genero = forms.CharField(label='Nombre del género', max_length=255, widget=forms.Select(choices=GENERO_OPCIONES))

class BuscarEmpresa(forms.Form):
    empresa = forms.CharField(label='Nombre de la empresa', max_length=255)

class BuscarValoracion(forms.Form):
    valoracion = forms.IntegerField(label='Valoracion', widget=forms.Select(choices=VALORACIONES_OPCIONES))

class TemaForm(forms.ModelForm):
    class Meta:
        model = Tema
        fields = ['titulo', 'descripcion']

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']

AppBase/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import *
from .forms import *

# Create your views here.
def inicio(request):
    try: 
        avatar = Avatar.objects.get(user=request.user.id)
        return render(request, 'inicio.html', {'url': avatar.imagen.url})
    except:
        return render(request, "inicio.html")
    
def AboutMe(request):
    return render(request, "aboutme.html")
    
#1er Círculo Inicio!!
@login_required   
def agregar_videojuego(request):
    if request.method == 'POST':
        mi_formulario = VideojuegosForm(request.POST)
        if mi_formulario.is_valid():
            data = mi_formulario.cleaned_data
            videojuego = Videojuego(nombre=request.POST['nombre'], fecha_salida=request.POST['fecha_salida'], genero=request.POST['genero'], empresa=request.POST['empresa'], descripcion=request.POST['descripcion'], valoracion=request.POST['valoracion'],)
            videojuego.save()
            return render(request, "inicio.html", {"mensaje": "Muy bien agregaste tu videojuego :D"})
        else:
            return render(request, "inicio.html", {"mensaje": "Formulario invalido"})
    else:
        mi_formulario = VideojuegosForm()
        return render(request, "agregar_videojuego.html", {"mi_formulario": mi_formulario})

@login_required  
def lista_videojuegos(request):
    orden = request.GET.get('orden', None)
    videojuegos = Videojuego.objects.all()
    if orden == 'lanzamiento':
        videojuegos = videojuegos.order_by('-fecha_salida')
    elif orden == 'valoracion':
        videojuegos = videojuegos.order_by('-valoracion')
    return render(request, "ver_videojuegos.html", {"videojuegos": videojuegos})

@login_required
def eliminar_videojuego(request, id):
    if request.method == 'POST':
        videojuego = Videojuego.objects.get(id=id)
        videojuego.delete()
        videojuego = Videojuego.objects.all()
        return HttpResponseRedirect('/l-videojuegos')

@login_required    
def editar_videojuego(request, id):
    videojuego = Videojuego.objects.get(id=id)
    if request.method == 'POST':
        mi_formulario = VideojuegosForm(request.POST)
        if mi_formulario.is_valid():
            data = mi_formulario.cleaned_data
            videojuego.nombre = data['nombre']
            videojuego.fecha_salida = data['fecha_salida']
            videojuego.genero = data['genero']
            videojuego.empresa = data['empresa']
            videojuego.descripcion = data['descripcion']
            videojuego.valoracion = data['valoracion']
            videojuego.save()
            return render(request, "inicio.html", {"mensaje": "Cambios realizados ;)"})
        else:
            return render(request, "inicio.html", {"mensaje": "Formulario invalido"})
    else:
        mi_formulario = VideojuegosForm(initial={
            "nombre": videojuego.nombre,
            "fecha_salida": videojuego.fecha_salida,
            "genero": videojuego.genero,
            "empresa": videojuego.empresa,
            "descripcion": videojuego.descripcion,
            "valoracion": videojuego.valoracion
        })
        return render(request, "editar_videojuegos.html", {"mi_formulario": mi_formulario, "id": videojuego.id})

@login_required    
def agregar_resena(request):
    mi_formulario = ResenaForm()
    if request.method == 'POST':
        mi_formulario = ResenaForm(request.POST)
        if mi_formulario.is_valid():
            mi_formulario.save()
            return HttpResponseRedirect('/l-resenas')
    return render(request, 'agregar_resena.html', {'mi_formulario': mi_formulario})

@login_required
def lista_resenas(request):
    resenas = Resena.objects.all()
    return render(request, 'lista_resenas.html', {'reseñas': resenas})

@login_required
def eliminar_resena(request, id):
    if request.method == 'POST':
        resena = Resena.objects.get(id=id)
        resena.delete()
        resena = Resena.objects.all()
        return HttpResponseRedirect('/l-resenas')

login_required    
def editar_resena(request, id):
    resena = Resena.objects.get(id=id)
    if request.method == 'POST':
        mi_formulario = ResenaForm(request.POST)
        if mi_formulario.is_valid():
            data = mi_formulario.cleaned_data
            resena.autor = data['autor']
            resena.contenido = data['contenido']
            resena.videojuego = data['videojuego']
            resena.save()
            return render(request, "inicio.html", {"mensaje": "Cambios realizados ;)"})
        else:
            return render(request, "inicio.html", {"mensaje": "Formulario invalido"})
    else:
        mi_formulario = ResenaForm(initial={
            "autor": resena.autor,
            "contenido": resena.contenido,
            "videojuego": resena.videojuego,
        })
        return render(request, "editar_resena.html", {"mi_formulario": mi_formulario, "id": resena.id})
#1er Círculo Fin!!

#2do Círculo Inicio!!
@login_required
def busqueda_videojuegos(request):
    return render(request, 'buscar_videojuegos.html')

@login_required
def buscar_nombre(request):
    if request.method == 'GET':
        form = BuscarNombre(request.GET)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            videojuegos = Videojuego.objects.filter(nombre__icontains=nombre)
            return render(request, 'res_busqueda_nombre.html', {'videojuegos': videojuegos, 'nombre': nombre})
    else:
        form = BuscarNombre()
    return render(request, 'busq_nombre.html', {'form': form})

@login_required
def buscar_genero(request):
    if request.method == 'GET':
        form = BuscarGenero(request.GET)
        if form.is_valid():
            genero = form.cleaned_data['genero']
            videojuegos = Videojuego.objects.filter(genero__icontains=genero)
            return render(request, 'res_busqueda_genero.html', {'videojuegos': videojuegos, 'genero': genero})
    else:
        form = BuscarGenero()
    return render(request, 'busq_genero.html', {'form': form})

@login_required
def buscar_empresa(request):
    if request.method == 'GET':
        form = BuscarEmpresa(request.GET)
        if form.is_valid():
            empresa = form.cleaned_data['empresa']
            videojuegos = Videojuego.objects.filter(empresa__icontains=empresa)
            return render(request, 'res_busqueda_empresa.html', {'videojuegos': videojuegos, 'empresa': empresa})
    else:
        form = BuscarEmpresa()
    return render(request, 'busq_empresa.html', {'form': form})

@login_required
def buscar_valoracion(request):
    if request.method == 'GET':
        form = BuscarValoracion(request.GET)
        if form.is_valid():
            valoracion = form.cleaned_data['valoracion']
            videojuegos = Videojuego.objects.filter(valoracion__icontains=valoracion)
            return render(request, 'res_busqueda_valoracion.html', {'videojuegos': videojuegos, 'valoracion': valoracion})
    else:
        form = BuscarValoracion()
    return render(request, 'busq_valoracion.html', {'form': form})
#2do Cícurlo Final!!

#3er Círculo Inicio!!
@login_required
def lista_temas(request):
    temas = Tema.objects.all()
    return render(request, 'foro.html', {'temas': temas})

@login_required
def crear_tema(request):
    if request.method == 'POST':
        form = TemaForm(request.POST)
        if form.is_valid():
            tema = form.save(commit=False)
            tema.creador = request.user
            tema.save()
            return HttpResponseRedirect('/foro')
    else:
        form = TemaForm()
    return render(request, 'crear_tema.html', {'form': form})

@login_required
def editar_tema(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    if request.method == 'POST':
        form = TemaForm(request.POST, instance=tema)
        if form.is_valid():
            tema = form.save()
            return HttpResponseRedirect('/foro')
    else:
        form = TemaForm(instance=tema)
    return render(request, 'editar_tema.html', {'form': form, 'tema': tema})

@login_required
def eliminar_tema(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    tema.delete()
    return HttpResponseRedirect('/foro')

@login_required
def detalle_tema(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    comentarios = Comentario.objects.filter(tema=tema)
    form = ComentarioForm()
    return render(request, 'detalle_tema.html', {'tema': tema, 'comentarios': comentarios, 'form': form})

@login_required
def crear_comentario(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.creador = request.user
            comentario.tema = tema
            comentario.save()
            return HttpResponseRedirect(reverse('DetalleTema', args=[tema.pk]))
    else:
        form = ComentarioForm()
    return render(request, 'crear_comentario.html', {'form': form})
#3er Círculo Final

#El 4to Círculo está en AppMensajes

AppBase/templates/aboutme.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/aboutme.css' %}">

    <h1>Hola! Soy Nicolás Jiménez Lamberti</h1>

    <img class="center" height="797px" src="{% static 'img/fotoPerfil.jpg' %}" alt="Imagen saludo">

    <body>
    <h5>Les voy a contar sobre mi!</h5>
    <p>Nací en 1994, soy de Buenos Aires, Argentina y amo los videojuegos!</p>
	<p>Soy Technical Artist, actualmente trabajando en Buho Animation Studios.
    <p>También soy Profesor y Tutor de Unreal en Image Campus, un rubro que se complementa bien con este, siempre me apasionó enseñar y transmitir conocimientos</p>
	<p>Ahora estoy por estos caminos empezando a programar, algo que siempre me llamó la atención, ya que siempre supe bastante de computación, disfruto mucho el aprender como funcionan las cosas</p>
	<p>Mi mayor objetivo en la vida fue trabajar en videojuegos, por eso quiero ampliar mis horizontes en nuevas prácticas dentro de este camino tan divertido.</p>
    <p>Actualmente estoy terminando este curso que es de Python orientado al desarrollo web en Coderhouse para automatizar procesos en mi pipeline de Rigging</p>
    <p>Si queres saber más de todo lo que hice acá les dejo mis repositorios en GitHub, saludos!!</p>

    <div style="margin-top: 20px;"></div>
    <a href="https://github.com/na1ku" target="_blank"><button>Visitar Github</button></a>
    </div>

    <div style="margin-top: 20px;">
        {% url 'Inicio' as url %}
        <button class="center" type="button" onclick="window.location.href='{{ url }}'">Volver a la Home</button>
    </div>
{% endblock contenidoQCambia %}

AppBase/templates/agregar_resena.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'css/agregar_resena.css' %}">

    <h1>Agregar Reseña</h1>
    <form method="POST">{% csrf_token %}
        {{ mi_formulario.as_p }}
        <button type="submit">Agregar</button>
    </form>
{% endblock contenidoQCambia %}

AppBase/templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Knight - Free Bootstrap 4 Product Landing Page Template</title>
    <meta name="description" content="Knight is a beautiful Bootstrap 4 template for product landing pages."/>

    <!--Inter UI font-->
    <link href="https://rsms.me/inter/inter-ui.css" rel="stylesheet">

    <!--vendors styles-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">

    <!-- Bootstrap CSS / Color Scheme -->
    <link rel="stylesheet" href="{% static 'css/default.css'%}" id="theme-color">
</head>
<body>

<!--navigation-->
<section class="smart-scroll">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md navbar-dark">
            <a class="navbar-brand heading-black" href="{% url 'Inicio' %}">
                HOME
            </a>
            <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span data-feather="grid"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'AboutMe' %}">About Me</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'Perfil' %}">Perfil</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'AppMensajes:Inbox' %}">Mensajes</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                    {% if user.is_authenticated %}
                        {% if url %}
                            <img height="60px" src="{{url}}" alt="avatar">
                        {% endif %}
                        <p>Bienvenido {{user.username}}</p>
                        <form id="logout-form" method="POST" action="{% url 'Logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="nav-link page-scroll d-flex flex-row align-items-center text-primary" style="background: none; border: none;">
                                <em data-feather="layout" width="18" height="18" class="mr-2"></em>
                                LOGOUT
                            </button>
                        </form>
                    {% else %}
                        <a class="nav-link page-scroll d-flex flex-row align-items-center text-primary" href="{% url 'Login' %}">
                            <em data-feather="layout" width="18" height="18" class="mr-2"></em>
                            LOGIN
                        </a>
                    {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</section>
{% if user.is_authenticated %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}
<!--hero header-->
{% if not user.is_authenticated %}
<section class="py-7 py-md-0 bg-hero" id="home">
    <div class="container">
        <div class="row vh-md-100">
            <div class="col-md-8 col-sm-10 col-12 mx-auto my-auto text-center">
                <h1 class="heading-black text-capitalize">Agregá y ordená todos tus videojuegos favoritos como más desees</h1>
                <p class="lead py-3">Ordenalos cronológicamente, valoralos, reseñalos, discutilo en el foro o habla con tus amigos. Clickeá en Features o scrolleá hacia abajo para acceder a lo que quieras.</p>
                <a class="btn btn-primary d-inline-flex flex-row align-items-center" href="{% url 'RegistroUsuarios' %}">
                    CREAR USUARIO
                    <em class="ml-2" data-feather="arrow-right"></em>
                </a>
            </div>
        </div>
    </div>
</section>
{% endif %}

<!-- features section -->
{% block contenidoQCambia %}
            
{% endblock contenidoQCambia %}

<section class="pt-6 pb-7" id="features">
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <div class="row feature-boxes">
                    <div class="col-md-6 box">
                        <div class="icon-box box-primary">
                            <a href="{% url 'ListaVideojuegos' %}">
                                <div class="icon-box-inner">
                                    <span data-feather="edit-3" width="35" height="35"></span>
                                    </div>
                                </div>
                            </a>
                        <h5>Crea tus listas de videojuegos favoritos</h5>
                        <p class="text-muted">Acá vas a poder guardarlos, valorarlos, ordenarlos y reseñarlos.</p>
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-success">
                            <a href="{% url 'BusquedaVideojuegos' %}">
                                <div class="icon-box-inner">
                                    <span data-feather="monitor" width="35" height="35"></span>
                                </div>
                            </a>
                        </div>
                        <h5>Info y data de videojuegos</h5>
                        <p class="text-muted">Buscá los videojuegos que quieras por nombre, empresa, género o valoración.</p>
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-danger">
                            <a href="{% url 'Foro' %}">
                                <div class="icon-box-inner">
                                    <span data-feather="layout" width="35" height="35"></span>
                                </div>
                            </a>
                        </div>
                        <h5>Foro</h5>
                        <p class="text-muted">Discutí y charla sobre temas variados a los videojuegos en este foro.</p>
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-info">
                            <a href="{% url 'AppMensajes:Inbox' %}">
                                <div class="icon-box-inner">
                                    <span data-feather="globe" width="35" height="35"></span>
                                </div>
                            </a>
                        </div>
                        <h5>Chat con amigos</h5>
                        <p class="text-muted">Chateá con tus amigos por mensajes privados</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-6">
            </div>
        </div>
    </div>
</section>
<!--footer-->
<footer class="py-6">
        <div class="row mt-5">
            <div class="col-12 text-muted text-center small-xl">
                &copy; 2019 Knight - All Rights Reserved
            </div>
        </div>
</footer>

<!--scroll to top-->
<div class="scroll-top">
    <i class="fa fa-angle-up" aria-hidden="true"></i>
</div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

AppBase/templates/busq_genero.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'css/busq_genero.css' %}">

    <form action="{% url 'BuscarGenero' %}" method="GET">{% csrf_token %}
        <p>Nombre del género de videojuego que queres buscar: <input type="text" name="genero" id=""></p>
        <button type="submit"> Buscar </button>
    </form>
{% endblock contenidoQCambia %}

AppBase/templates/busq_nombre.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'css/busq_nombre.css' %}">

    <form action="{% url 'BuscarNombre' %}" method="GET">{% csrf_token %}
        <p>Nombre de videojuego que queres buscar: <input type="text" name="nombre" id=""></p>
        <button type="submit"> Buscar </button>
    </form>
{% endblock contenidoQCambia %}